serial:
  displayFormat: hex
  displayMode: all
  sendFormat: text
  appendNewline: true
  newlineType: lf
  autoScroll: false
ble:
  displayFormat: hex
  autoScroll: true
  inputFormat: text
  withoutResponse: false
  configCollapsed: false
  gattCollapsed: false
  panelCollapsed: false
waveform:
  displayRows: 20
  refreshInterval: 100
  sidebarCollapsed: false
gh3036Channel:
  connectionType: serial
  serialPort: COM10
  bleDevice: ''
  txChar: 00000004-0000-1000-8000-00805f9b34fb
  rxChar: 00000003-0000-1000-8000-00805f9b34fb
